services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Typo3OnAws\AwsDashboardWidgets\:
    resource: '../Classes/*'

  dashboard.widget.Typo3OnAws.AwsDashboardWidgets.AwsGeneralInformationWidget:
    class: 'Typo3OnAws\AwsDashboardWidgets\Widgets\AwsGeneralInformationWidget'
    arguments:
      $options: []
    tags:
      - name: dashboard.widget
        identifier: 'AwsGeneralInformationWidget'
        groupNames: 'general'
        title: 'LLL:EXT:aws_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.AwsGeneralInformationWidget.title'
        description: 'LLL:EXT:aws_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.AwsGeneralInformationWidget.description'
        iconIdentifier: 'content-widget-text'
        height: 'medium'
        width: 'large'
